package enums;

public enum Context {
    USERNAME,
    TEST,
    ADDRESS,
    SELECTED_CATALOG_NAME,
    VENDOR_BASIC_INFO,
    HOME_VENDOR_RESPONSE,
    HOME_VENDOR_LIST,
    VENDOR_DETAIL,
    PRODUCT_LIST,
    ADDRESS_LIST,
    BANABI_VENDOR_INFO,
    BANABI_VENDOR_RESPONSE,
    BANNER_LIST,
    PRODUCT

}
