package enums;

public enum Context {
    USERNAME,
    TEST,
    ADDRESS,
    SELECTED_CATALOG_NAME,
    VENDOR_BASIC_INFO,
    HOME_VENDOR_RESPONSE,
    HOME_VENDOR_LIST,
    VENDOR_DETAIL_RESPONSE,
    PRODUCT_LIST,
    ADDRESS_LIST,
    BANABI_VENDOR_INFO,
    BANABI_VENDOR_RESPONSE,
    BANNER_LIST,
    PRODUCT_DETAIL_DATA,
    SPLASH_RESPONSE,
    SPLASH_RESPONSE_DATA,
    HOME_PLATFORM_RESPONSE,
    SELECTED_VENDOR,
    SELECTED_PRODUCT_CATEGORY,
    SELECTED_SUB_PRODUCT_CATEGORY,
    VENDOR_CATEGORY_PRODUCTS_RES,
    SELECTED_PRODUCT,
    BASKET_ID,
    VENDOR_PRODUCT_SEARCH_RESPONSE,
    GET_FAVORITE_VENDORS_RESPONSE,
    ADDED_FAVORITE_VENDOR_ID_LIST,
    GET_VENDOR_FAVORITE_PRODUCTS_RESPONSE,
    SELECTED_PRODUCT_ID_LIST

}
